import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleAnalytics } from '@next/third-parties/google'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "google-site-verification=JzZJfFNYQlrXHnoD2sf5IemcNcfX1yBll85Juu7ZDog",
  },
};

export default function RootLayout({
  children,
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >      
      
      <body className="min-h-full flex flex-col">{children}</body>
      <GoogleAnalytics gaId="G-0NTXY7JMK5" />


    </html>
   
  );
}
